# Generated by Django 3.2.12 on 2022-02-26 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='category name')),
                ('description', models.CharField(max_length=500, verbose_name='category description')),
            ],
            options={
                'verbose_name': 'resource category',
                'verbose_name_plural': 'resource categories',
            },
        ),
        migrations.CreateModel(
            name='ResourceSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='subcategory name')),
                ('description', models.CharField(max_length=500, verbose_name='subcategory description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='available_resources.resourcecategory')),
            ],
            options={
                'verbose_name': 'resource category',
                'verbose_name_plural': 'resource categories',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='resource name')),
                ('description', models.TextField(verbose_name='resource description')),
                ('donor_name', models.CharField(max_length=255, verbose_name='name')),
                ('donor_contact_name', models.CharField(blank=True, max_length=255, verbose_name='contact name')),
                ('donor_email', models.EmailField(max_length=255, verbose_name='email address')),
                ('donor_phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='phone number')),
                ('donor_details', models.JSONField(blank=True, null=True, verbose_name='details')),
                ('donor_type', models.SmallIntegerField(choices=[(0, 'Individual'), (1, 'Company'), (2, 'Public Body'), (3, 'Non-Profit')], db_index=True, verbose_name='type')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='available_resources.resourcesubcategory')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
            },
        ),
    ]
