# Generated by Django 3.2.12 on 2022-02-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='donor_county',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='county'),
        ),
    ]
