# Generated by Django 3.2.12 on 2022-02-27 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
        ('available_resources', '0003_auto_20220227_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproductsresource',
            name='unit_type',
            field=models.CharField(max_length=10, verbose_name='unit type'),
        ),
        migrations.RenameModel(
            old_name='FoodProductsResource',
            new_name='ProductsResource',
        ),
        migrations.CreateModel(
            name='VolunteeringResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='resource name')),
                ('county_coverage', models.CharField(
                    choices=[('AB', 'Alba'), ('AR', 'Arad'), ('AG', 'Argeș'), ('BC', 'Bacău'), ('BH', 'Bihor'),
                             ('BN', 'Bistrița-Năsăud'), ('BT', 'Botoșani'), ('BV', 'Brașov'), ('BR', 'Brăila'),
                             ('B', 'București'), ('BZ', 'Buzău'), ('CL', 'Călărași'), ('CS', 'Caraș-Severin'),
                             ('CJ', 'Cluj'), ('CT', 'Constanța'), ('CV', 'Covasna'), ('DB', 'Dâmbovița'),
                             ('DJ', 'Dolj'), ('GL', 'Galați'), ('GR', 'Giurgiu'), ('GJ', 'Gorj'), ('HR', 'Harghita'),
                             ('HD', 'Hunedoara'), ('IL', 'Ialomița'), ('IS', 'Iași'), ('IF', 'Ilfov'),
                             ('MM', 'Maramureș'), ('MH', 'Mehedinți'), ('MS', 'Mureș'), ('NT', 'Neamț'), ('OT', 'Olt'),
                             ('PH', 'Prahova'), ('SM', 'Satu Mare'), ('SJ', 'Sălaj'), ('SB', 'Sibiu'),
                             ('SV', 'Suceava'), ('TR', 'Teleorman'), ('TM', 'Timiș'), ('TL', 'Tulcea'),
                             ('VS', 'Vaslui'), ('VL', 'Vâlcea'), ('VN', 'Vrancea'), ('RO', 'Național')], max_length=2,
                    verbose_name='county')),
                ('type', models.PositiveSmallIntegerField(
                    choices=[(0, 'psychologist'), (1, 'medic'), (2, 'nurse'), (3, 'lawyer'), (4, 'cook'),
                             (5, 'manager')], db_index=True, verbose_name='volunteer type')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donor')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  to='available_resources.resourcesubcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='resource name')),
                ('description',
                 models.CharField(blank=True, default='', max_length=500, verbose_name='resource description')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donor')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  to='available_resources.resourcesubcategory')),
            ],
            options={
                'abstract': False,
            },
        )
    ]
