# Generated by Django 3.2.12 on 2022-03-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0003_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='phone number'),
        ),
    ]
