# Generated by Django 3.2.12 on 2022-03-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_volunteering', '0011_alter_volunteeringrequest_made_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeringoffer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
