# Generated by Django 3.2.12 on 2022-03-03 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='category name')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='category description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_coverage', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AB', 'Alba'), ('AR', 'Arad'), ('AG', 'Argeș'), ('BC', 'Bacău'), ('BH', 'Bihor'), ('BN', 'Bistrița-Năsăud'), ('BT', 'Botoșani'), ('BV', 'Brașov'), ('BR', 'Brăila'), ('B', 'București'), ('BZ', 'Buzău'), ('CL', 'Călărași'), ('CS', 'Caraș-Severin'), ('CJ', 'Cluj'), ('CT', 'Constanța'), ('CV', 'Covasna'), ('DB', 'Dâmbovița'), ('DJ', 'Dolj'), ('GL', 'Galați'), ('GR', 'Giurgiu'), ('GJ', 'Gorj'), ('HR', 'Harghita'), ('HD', 'Hunedoara'), ('IL', 'Ialomița'), ('IS', 'Iași'), ('IF', 'Ilfov'), ('MM', 'Maramureș'), ('MH', 'Mehedinți'), ('MS', 'Mureș'), ('NT', 'Neamț'), ('OT', 'Olt'), ('PH', 'Prahova'), ('SM', 'Satu Mare'), ('SJ', 'Sălaj'), ('SB', 'Sibiu'), ('SV', 'Suceava'), ('TR', 'Teleorman'), ('TM', 'Timiș'), ('TL', 'Tulcea'), ('VS', 'Vaslui'), ('VL', 'Vâlcea'), ('VN', 'Vrancea')], max_length=124, null=True, verbose_name='county coverage')),
                ('town', models.CharField(blank=True, max_length=100, null=True, verbose_name='town')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='description')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='added on')),
                ('status', models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified'), ('D', 'Deactivated'), ('C', 'Complete')], default='NV', max_length=5, verbose_name='status')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Product')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='total units')),
                ('packaging_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='packaging')),
                ('unit_type', models.CharField(max_length=10, verbose_name='unit type')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='expiration date')),
                ('stock', models.PositiveSmallIntegerField(blank=True, help_text='How many units of this type are left', null=True, verbose_name='Stock')),
                ('kids_age', models.CharField(blank=True, max_length=100, null=True, verbose_name='age')),
                ('other_textiles', models.TextField(blank=True, null=True, verbose_name='other')),
                ('tent_capacity', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='capacity')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_item.category')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='donor')),
            ],
            options={
                'verbose_name': 'item offer',
                'verbose_name_plural': 'item offers',
            },
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_coverage', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AB', 'Alba'), ('AR', 'Arad'), ('AG', 'Argeș'), ('BC', 'Bacău'), ('BH', 'Bihor'), ('BN', 'Bistrița-Năsăud'), ('BT', 'Botoșani'), ('BV', 'Brașov'), ('BR', 'Brăila'), ('B', 'București'), ('BZ', 'Buzău'), ('CL', 'Călărași'), ('CS', 'Caraș-Severin'), ('CJ', 'Cluj'), ('CT', 'Constanța'), ('CV', 'Covasna'), ('DB', 'Dâmbovița'), ('DJ', 'Dolj'), ('GL', 'Galați'), ('GR', 'Giurgiu'), ('GJ', 'Gorj'), ('HR', 'Harghita'), ('HD', 'Hunedoara'), ('IL', 'Ialomița'), ('IS', 'Iași'), ('IF', 'Ilfov'), ('MM', 'Maramureș'), ('MH', 'Mehedinți'), ('MS', 'Mureș'), ('NT', 'Neamț'), ('OT', 'Olt'), ('PH', 'Prahova'), ('SM', 'Satu Mare'), ('SJ', 'Sălaj'), ('SB', 'Sibiu'), ('SV', 'Suceava'), ('TR', 'Teleorman'), ('TM', 'Timiș'), ('TL', 'Tulcea'), ('VS', 'Vaslui'), ('VL', 'Vâlcea'), ('VN', 'Vrancea')], max_length=124, null=True, verbose_name='county coverage')),
                ('town', models.CharField(blank=True, max_length=100, null=True, verbose_name='town')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='description')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='added on')),
                ('status', models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified'), ('D', 'Deactivated'), ('C', 'Complete')], default='NV', max_length=5, verbose_name='status')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Product')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='total units')),
                ('packaging_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='packaging')),
                ('unit_type', models.CharField(max_length=10, verbose_name='unit type')),
                ('stock', models.PositiveSmallIntegerField(blank=True, help_text='How many units are still needed', null=True, verbose_name='Stock')),
                ('kids_age', models.CharField(blank=True, max_length=100, null=True, verbose_name='age')),
                ('other_textiles', models.TextField(blank=True, null=True, verbose_name='other')),
                ('tent_capacity', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='capacity')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_item.category')),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
            ],
            options={
                'verbose_name': 'item request',
                'verbose_name_plural': 'item requests',
            },
        ),
        migrations.CreateModel(
            name='TextileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='category name')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='category description')),
            ],
            options={
                'verbose_name': 'Textile Category',
                'verbose_name_plural': 'Textile Categories',
            },
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_units', models.PositiveSmallIntegerField(default=0, verbose_name='total units')),
                ('description', models.TextField(blank=True, default='', max_length=500, verbose_name='description')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='added on')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_item.itemrequest')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_item.itemoffer')),
            ],
            options={
                'verbose_name': 'Offer - Request',
                'verbose_name_plural': 'Offer - Request',
            },
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='textile_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_item.textilecategory'),
        ),
        migrations.AddField(
            model_name='itemoffer',
            name='textile_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_item.textilecategory'),
        ),
    ]
