# Generated by Django 3.2.12 on 2022-03-01 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='category name')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='category description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ItemOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='resource name')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='resource description')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='resource added on')),
                ('available_from', models.DateTimeField(auto_now_add=True, verbose_name='resource available from')),
                ('available_until', models.DateTimeField(null=True, verbose_name='resource available until')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='expiration date')),
                ('packaging_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='packaging type')),
                ('county_coverage', models.CharField(choices=[('AB', 'Alba'), ('AR', 'Arad'), ('AG', 'Argeș'), ('BC', 'Bacău'), ('BH', 'Bihor'), ('BN', 'Bistrița-Năsăud'), ('BT', 'Botoșani'), ('BV', 'Brașov'), ('BR', 'Brăila'), ('B', 'București'), ('BZ', 'Buzău'), ('CL', 'Călărași'), ('CS', 'Caraș-Severin'), ('CJ', 'Cluj'), ('CT', 'Constanța'), ('CV', 'Covasna'), ('DB', 'Dâmbovița'), ('DJ', 'Dolj'), ('GL', 'Galați'), ('GR', 'Giurgiu'), ('GJ', 'Gorj'), ('HR', 'Harghita'), ('HD', 'Hunedoara'), ('IL', 'Ialomița'), ('IS', 'Iași'), ('IF', 'Ilfov'), ('MM', 'Maramureș'), ('MH', 'Mehedinți'), ('MS', 'Mureș'), ('NT', 'Neamț'), ('OT', 'Olt'), ('PH', 'Prahova'), ('SM', 'Satu Mare'), ('SJ', 'Sălaj'), ('SB', 'Sibiu'), ('SV', 'Suceava'), ('TR', 'Teleorman'), ('TM', 'Timiș'), ('TL', 'Tulcea'), ('VS', 'Vaslui'), ('VL', 'Vâlcea'), ('VN', 'Vrancea'), ('RO', 'Național')], max_length=2, verbose_name='county')),
                ('pickup_town', models.CharField(max_length=100, verbose_name='pickup town')),
                ('in_use_by', models.TextField(blank=True, null=True, verbose_name='in use by')),
                ('total_units', models.PositiveSmallIntegerField(default=0, verbose_name='total units')),
                ('units_left', models.PositiveSmallIntegerField(blank=True, help_text='How many units of this type are left', null=True, verbose_name='reuses left')),
                ('unit_type', models.CharField(max_length=10, verbose_name='unit type')),
                ('weight', models.PositiveSmallIntegerField(default=0, verbose_name='usable weight')),
                ('is_infinitely_reusable', models.BooleanField(default=False, verbose_name='is infinitely reusable')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'item offer',
                'verbose_name_plural': 'item offers',
            },
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='resource name')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='resource description')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='resource added on')),
                ('county_coverage', models.CharField(choices=[('AB', 'Alba'), ('AR', 'Arad'), ('AG', 'Argeș'), ('BC', 'Bacău'), ('BH', 'Bihor'), ('BN', 'Bistrița-Năsăud'), ('BT', 'Botoșani'), ('BV', 'Brașov'), ('BR', 'Brăila'), ('B', 'București'), ('BZ', 'Buzău'), ('CL', 'Călărași'), ('CS', 'Caraș-Severin'), ('CJ', 'Cluj'), ('CT', 'Constanța'), ('CV', 'Covasna'), ('DB', 'Dâmbovița'), ('DJ', 'Dolj'), ('GL', 'Galați'), ('GR', 'Giurgiu'), ('GJ', 'Gorj'), ('HR', 'Harghita'), ('HD', 'Hunedoara'), ('IL', 'Ialomița'), ('IS', 'Iași'), ('IF', 'Ilfov'), ('MM', 'Maramureș'), ('MH', 'Mehedinți'), ('MS', 'Mureș'), ('NT', 'Neamț'), ('OT', 'Olt'), ('PH', 'Prahova'), ('SM', 'Satu Mare'), ('SJ', 'Sălaj'), ('SB', 'Sibiu'), ('SV', 'Suceava'), ('TR', 'Teleorman'), ('TM', 'Timiș'), ('TL', 'Tulcea'), ('VS', 'Vaslui'), ('VL', 'Vâlcea'), ('VN', 'Vrancea'), ('RO', 'Național')], max_length=2, verbose_name='county')),
                ('pickup_town', models.CharField(max_length=100, verbose_name='pickup town')),
                ('total_units', models.PositiveSmallIntegerField(default=0, verbose_name='total units')),
                ('unit_type', models.CharField(max_length=10, verbose_name='unit type')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'item request',
                'verbose_name_plural': 'item requests',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='subcategory name')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='subcategory description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_item.category')),
            ],
            options={
                'verbose_name': 'subcategory',
                'verbose_name_plural': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_item.itemrequest')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_item.itemoffer')),
            ],
            options={
                'verbose_name': 'Offer - Request',
                'verbose_name_plural': 'Offer - Request',
            },
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_item.subcategory'),
        ),
        migrations.AddField(
            model_name='itemoffer',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_item.subcategory'),
        ),
    ]
