# Generated by Django 3.2.12 on 2022-03-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemoffer',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='itemoffer',
            name='tent_capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='total units'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='tent_capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='capacity'),
        ),
    ]
