# Generated by Django 3.2.12 on 2022-03-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerequest',
            name='total_units',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='total units'),
        ),
    ]
