# Generated by Django 3.2.12 on 2022-03-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0002_auto_20220303_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequest',
            name='expiration_date',
        ),
        migrations.AlterField(
            model_name='itemoffer',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='expiration date'),
        ),
    ]
