# Generated by Django 3.2.12 on 2022-03-02 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0002_resourcerequest_total_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
