# Generated by Django 3.2.12 on 2022-03-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0003_resourcerequest_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='units_left',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many units of this type are still needed', null=True, verbose_name='units left'),
        ),
    ]
