# Generated by Django 3.2.12 on 2022-03-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0003_auto_20220303_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoffer',
            name='pickup_address',
            field=models.CharField(default='', max_length=100, verbose_name='pickup address'),
            preserve_default=False,
        ),
    ]
