# Generated by Django 3.2.12 on 2022-03-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0003_auto_20220304_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemoffer',
            options={'verbose_name': 'item offer', 'verbose_name_plural': 'item offers'},
        ),
        migrations.AlterModelOptions(
            name='itemrequest',
            options={'verbose_name': 'item request', 'verbose_name_plural': 'item requests'},
        ),
    ]
