# Generated by Django 3.2.12 on 2022-03-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0004_itemoffer_pickup_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemoffer',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='pickup address'),
        ),
    ]
