# Generated by Django 3.2.12 on 2022-03-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0005_alter_itemrequest_county_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemoffer',
            name='textile_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_item.textilecategory', verbose_name='textile category'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified'), ('D', 'Deactivated'), ('C', 'Solved')], default='NV', max_length=5, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='textile_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_item.textilecategory', verbose_name='textile category'),
        ),
    ]
