# Generated by Django 3.2.12 on 2022-03-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0005_auto_20220302_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoffer',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified')], default='NV', max_length=5, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified')], default='NV', max_length=5, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='itemoffer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
