# Generated by Django 3.2.12 on 2022-03-02 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0006_auto_20220302_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemoffer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='date_created',
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='added on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='category description'),
        ),
        migrations.AlterField(
            model_name='itemoffer',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='resource description'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='resource description'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='subcategory description'),
        ),
    ]
