# Generated by Django 3.2.12 on 2022-03-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0007_auto_20220302_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemoffer',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='itemoffer',
            name='available_until',
        ),
    ]
