# Generated by Django 3.2.12 on 2022-03-03 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0002_auto_20220303_0153'),
        ('app_item', '0007_auto_20220303_0250'),
    ]

    operations = [
    ]
