# Generated by Django 3.2.12 on 2022-03-03 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0003_auto_20220303_0230'),
        ('app_item', '0008_merge_0002_auto_20220303_0153_0007_auto_20220303_0250'),
    ]

    operations = [
    ]
