# Generated by Django 3.2.12 on 2022-03-07 20:04

from django.db import migrations, models
import revm_site.validators


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0008_alter_itemoffer_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemoffer',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, validators=[revm_site.validators.validate_date_disallow_past], verbose_name='expiration date'),
        ),
    ]
