# Generated by Django 3.2.12 on 2022-03-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0009_auto_20220302_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='category description'),
        ),
    ]
