# Generated by Django 3.2.12 on 2022-03-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0009_merge_20220303_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemoffer',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='pickup_address',
        ),
        migrations.AlterField(
            model_name='itemoffer',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified'), ('D', 'Deactivated'), ('C', 'Complete')], default='NV', max_length=5, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified'), ('D', 'Deactivated'), ('C', 'Complete')], default='NV', max_length=5, verbose_name='status'),
        ),
    ]
