# Generated by Django 3.2.12 on 2022-03-13 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_item', '0010_auto_20220310_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='made_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_account.customuser', verbose_name='requested by'),
            preserve_default=False,
        ),
    ]
