# Generated by Django 3.2.12 on 2022-03-02 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0010_alter_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='category name')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='category description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='itemoffer',
            old_name='total_units',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='itemrequest',
            old_name='total_units',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='itemoffer',
            name='in_use_by',
        ),
        migrations.RemoveField(
            model_name='itemoffer',
            name='is_infinitely_reusable',
        ),
        migrations.RemoveField(
            model_name='itemoffer',
            name='units_left',
        ),
        migrations.RemoveField(
            model_name='itemoffer',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='units_left',
        ),
        migrations.AddField(
            model_name='itemoffer',
            name='kids_age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='itemoffer',
            name='other_textiles',
            field=models.TextField(blank=True, null=True, verbose_name='other'),
        ),
        migrations.AddField(
            model_name='itemoffer',
            name='stock',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, help_text='How many units of this type are left', null=True, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='itemoffer',
            name='tent_capacity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='capacity'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expiration date'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='kids_age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='other_textiles',
            field=models.TextField(blank=True, null=True, verbose_name='other'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='packaging_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='packaging'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='stock',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, help_text='How many units of this type are left', null=True, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='tent_capacity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='itemoffer',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='itemoffer',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='itemoffer',
            name='packaging_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='packaging'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='itemoffer',
            name='textile_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_item.textilecategory'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='textile_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_item.textilecategory'),
        ),
    ]
