# Generated by Django 3.2.12 on 2022-03-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0011_auto_20220302_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemoffer',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='itemoffer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_item.category'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_item.category'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='stock',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, help_text='How many units are still needed', null=True, verbose_name='Stock'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
