# Generated by Django 3.2.12 on 2022-03-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0011_alter_itemrequest_made_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='total units'),
        ),
    ]
