# Generated by Django 3.2.12 on 2022-03-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0012_auto_20220302_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textilecategory',
            options={'verbose_name': 'Textile Category', 'verbose_name_plural': 'Textile Categories'},
        ),
    ]
