# Generated by Django 3.2.12 on 2022-03-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0012_alter_itemrequest_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='total units'),
        ),
    ]
