# Generated by Django 3.2.12 on 2022-03-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_other', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otheroffer',
            options={'verbose_name': 'other offer', 'verbose_name_plural': 'other offers (0)'},
        ),
        migrations.AlterModelOptions(
            name='otherrequest',
            options={'verbose_name': 'other request', 'verbose_name_plural': 'other request (0)'},
        ),
    ]
