# Generated by Django 3.2.12 on 2022-03-03 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemoffer',
            options={'verbose_name': 'item offer', 'verbose_name_plural': 'item offers (2)'},
        ),
        migrations.AlterModelOptions(
            name='itemrequest',
            options={'verbose_name': 'item request', 'verbose_name_plural': 'item requests (0)'},
        ),
        migrations.AlterField(
            model_name='itemoffer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_item.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='itemoffer',
            name='textile_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_item.textilecategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_item.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='textile_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_item.textilecategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_item.itemrequest', verbose_name='request'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_item.itemoffer', verbose_name='donation'),
        ),
    ]
