# Generated by Django 3.2.12 on 2022-03-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0009_alter_itemoffer_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemoffer',
            old_name='kids_age',
            new_name='textile_size',
        ),
        migrations.RenameField(
            model_name='itemrequest',
            old_name='kids_age',
            new_name='textile_size',
        ),
        migrations.AlterField(
            model_name='itemoffer',
            name='textile_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='textile size'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='textile_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='textile size'),
        ),
    ]
