# Generated by Django 3.2.12 on 2022-03-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified'), ('D', 'Deactivated'), ('C', 'Complete')], default='NV', max_length=5, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='transportservicerequest',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified'), ('D', 'Deactivated'), ('C', 'Complete')], default='NV', max_length=5, verbose_name='status'),
        ),
    ]
