# Generated by Django 3.2.12 on 2022-03-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='availability',
            field=models.CharField(choices=[('WK', 'Available in weekend'), ('WD', 'Available in week day'), ('A', 'Available anytime'), ('FI', 'Fixed intervals')], default='WK', max_length=2, verbose_name='availability'),
        ),
    ]
