# Generated by Django 3.2.12 on 2022-03-02 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_transport_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportserviceoffer',
            name='available_anytime',
        ),
        migrations.RemoveField(
            model_name='transportserviceoffer',
            name='available_in_weekday',
        ),
        migrations.RemoveField(
            model_name='transportserviceoffer',
            name='available_in_weekend',
        ),
        migrations.RemoveField(
            model_name='transportserviceoffer',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='transportservicerequest',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='transportserviceoffer',
            name='availability',
            field=models.CharField(choices=[('WK', 'Available in weekend'), ('WD', 'Available in week day'), ('A', 'Available anytime'), ('FI', 'Fixed intervals')], default='WK', max_length=2, verbose_name='availability'),
        ),
        migrations.AddField(
            model_name='transportserviceoffer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_transport_service.category'),
        ),
        migrations.AddField(
            model_name='transportservicerequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_transport_service.category'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_transport_service.transportservicerequest'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_transport_service.transportserviceoffer'),
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='available_seats',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='available seats'),
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transportservicerequest',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
