# Generated by Django 3.2.12 on 2022-03-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_service', '0002_auto_20220303_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportservicerequest',
            name='available_seats',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='needed seats'),
        ),
    ]
