# Generated by Django 3.2.12 on 2022-03-03 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_service', '0002_alter_transportserviceoffer_availability'),
        ('app_transport_service', '0002_alter_transportserviceoffer_county_coverage'),
    ]

    operations = [
    ]
