# Generated by Django 3.2.12 on 2022-03-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_service', '0002_auto_20220302_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportserviceoffer',
            name='availability_interval_from',
            field=models.TimeField(blank=True, null=True, verbose_name='availability from hour'),
        ),
        migrations.AddField(
            model_name='transportserviceoffer',
            name='availability_interval_to',
            field=models.TimeField(blank=True, null=True, verbose_name='availability until hour'),
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='available_from',
            field=models.DateField(verbose_name='available from'),
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='available_until',
            field=models.DateField(null=True, verbose_name='available until'),
        ),
    ]
