# Generated by Django 3.2.12 on 2022-03-03 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_service', '0003_auto_20220303_0230'),
        ('app_transport_service', '0003_merge_20220303_0301'),
    ]

    operations = [
    ]
