# Generated by Django 3.2.12 on 2022-03-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_service', '0003_auto_20220302_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
