# Generated by Django 3.2.12 on 2022-03-02 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_service', '0003_auto_20220302_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportservicerequest',
            name='available_seats',
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='transport date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='units',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='units'),
        ),
        migrations.AddField(
            model_name='transportservicerequest',
            name='seats_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='number of seats'),
        ),
    ]
