# Generated by Django 3.2.12 on 2022-03-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_service', '0004_auto_20220302_1240'),
        ('app_transport_service', '0004_delete_subcategory'),
    ]

    operations = [
    ]
