# Generated by Django 3.2.12 on 2022-03-02 15:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_service', '0005_merge_0004_auto_20220302_1240_0004_delete_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportserviceoffer',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='transportserviceoffer',
            name='available_until',
        ),
        migrations.RemoveField(
            model_name='transportserviceoffer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transportserviceoffer',
            name='town',
        ),
        migrations.RemoveField(
            model_name='transportserviceoffer',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='transportserviceoffer',
            name='volume_unit',
        ),
        migrations.RemoveField(
            model_name='transportservicerequest',
            name='county_coverage',
        ),
        migrations.RemoveField(
            model_name='transportservicerequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transportservicerequest',
            name='seats_number',
        ),
        migrations.RemoveField(
            model_name='transportservicerequest',
            name='town',
        ),
        migrations.RemoveField(
            model_name='transportservicerequest',
            name='type',
        ),
        migrations.RemoveField(
            model_name='transportservicerequest',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='transportservicerequest',
            name='volume_unit',
        ),
        migrations.AddField(
            model_name='transportserviceoffer',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified')], default='NV', max_length=5, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='transportservicerequest',
            name='available_seats',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='available seats'),
        ),
        migrations.AddField(
            model_name='transportservicerequest',
            name='from_city',
            field=models.CharField(default='', max_length=150, verbose_name='From city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportservicerequest',
            name='from_county',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AB', 'Alba'), ('AR', 'Arad'), ('AG', 'Argeș'), ('BC', 'Bacău'), ('BH', 'Bihor'), ('BN', 'Bistrița-Năsăud'), ('BT', 'Botoșani'), ('BV', 'Brașov'), ('BR', 'Brăila'), ('B', 'București'), ('BZ', 'Buzău'), ('CL', 'Călărași'), ('CS', 'Caraș-Severin'), ('CJ', 'Cluj'), ('CT', 'Constanța'), ('CV', 'Covasna'), ('DB', 'Dâmbovița'), ('DJ', 'Dolj'), ('GL', 'Galați'), ('GR', 'Giurgiu'), ('GJ', 'Gorj'), ('HR', 'Harghita'), ('HD', 'Hunedoara'), ('IL', 'Ialomița'), ('IS', 'Iași'), ('IF', 'Ilfov'), ('MM', 'Maramureș'), ('MH', 'Mehedinți'), ('MS', 'Mureș'), ('NT', 'Neamț'), ('OT', 'Olt'), ('PH', 'Prahova'), ('SM', 'Satu Mare'), ('SJ', 'Sălaj'), ('SB', 'Sibiu'), ('SV', 'Suceava'), ('TR', 'Teleorman'), ('TM', 'Timiș'), ('TL', 'Tulcea'), ('VS', 'Vaslui'), ('VL', 'Vâlcea'), ('VN', 'Vrancea'), ('RO', 'Național')], default='', max_length=127, verbose_name='From county'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportservicerequest',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified')], default='NV', max_length=5, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='transportservicerequest',
            name='to_city',
            field=models.CharField(default='', max_length=150, verbose_name='From city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportservicerequest',
            name='to_county',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AB', 'Alba'), ('AR', 'Arad'), ('AG', 'Argeș'), ('BC', 'Bacău'), ('BH', 'Bihor'), ('BN', 'Bistrița-Năsăud'), ('BT', 'Botoșani'), ('BV', 'Brașov'), ('BR', 'Brăila'), ('B', 'București'), ('BZ', 'Buzău'), ('CL', 'Călărași'), ('CS', 'Caraș-Severin'), ('CJ', 'Cluj'), ('CT', 'Constanța'), ('CV', 'Covasna'), ('DB', 'Dâmbovița'), ('DJ', 'Dolj'), ('GL', 'Galați'), ('GR', 'Giurgiu'), ('GJ', 'Gorj'), ('HR', 'Harghita'), ('HD', 'Hunedoara'), ('IL', 'Ialomița'), ('IS', 'Iași'), ('IF', 'Ilfov'), ('MM', 'Maramureș'), ('MH', 'Mehedinți'), ('MS', 'Mureș'), ('NT', 'Neamț'), ('OT', 'Olt'), ('PH', 'Prahova'), ('SM', 'Satu Mare'), ('SJ', 'Sălaj'), ('SB', 'Sibiu'), ('SV', 'Suceava'), ('TR', 'Teleorman'), ('TM', 'Timiș'), ('TL', 'Tulcea'), ('VS', 'Vaslui'), ('VL', 'Vâlcea'), ('VN', 'Vrancea'), ('RO', 'Național')], default='', max_length=127, verbose_name='To county'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='availability_interval_from',
            field=models.TimeField(blank=True, null=True, verbose_name='from hour'),
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='availability_interval_to',
            field=models.TimeField(blank=True, null=True, verbose_name='until hour'),
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='county_coverage',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AB', 'Alba'), ('AR', 'Arad'), ('AG', 'Argeș'), ('BC', 'Bacău'), ('BH', 'Bihor'), ('BN', 'Bistrița-Năsăud'), ('BT', 'Botoșani'), ('BV', 'Brașov'), ('BR', 'Brăila'), ('B', 'București'), ('BZ', 'Buzău'), ('CL', 'Călărași'), ('CS', 'Caraș-Severin'), ('CJ', 'Cluj'), ('CT', 'Constanța'), ('CV', 'Covasna'), ('DB', 'Dâmbovița'), ('DJ', 'Dolj'), ('GL', 'Galați'), ('GR', 'Giurgiu'), ('GJ', 'Gorj'), ('HR', 'Harghita'), ('HD', 'Hunedoara'), ('IL', 'Ialomița'), ('IS', 'Iași'), ('IF', 'Ilfov'), ('MM', 'Maramureș'), ('MH', 'Mehedinți'), ('MS', 'Mureș'), ('NT', 'Neamț'), ('OT', 'Olt'), ('PH', 'Prahova'), ('SM', 'Satu Mare'), ('SJ', 'Sălaj'), ('SB', 'Sibiu'), ('SV', 'Suceava'), ('TR', 'Teleorman'), ('TM', 'Timiș'), ('TL', 'Tulcea'), ('VS', 'Vaslui'), ('VL', 'Vâlcea'), ('VN', 'Vrancea'), ('RO', 'Național')], max_length=127, verbose_name='county coverage'),
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'National'), (2, 'County')], default=1, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='weight_capacity',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='weight_unit',
            field=models.CharField(blank=True, default='t', max_length=3, null=True, verbose_name='weight unit'),
        ),
        migrations.AlterField(
            model_name='transportservicerequest',
            name='has_refrigeration',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transportservicerequest',
            name='weight_capacity',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='transportservicerequest',
            name='weight_unit',
            field=models.CharField(blank=True, default='t', max_length=3, null=True, verbose_name='weight unit'),
        ),
    ]
