# Generated by Django 3.2.12 on 2022-03-07 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_transport_service', '0006_alter_transportservicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_account.customuser', verbose_name='donor'),
            preserve_default=False,
        ),
    ]
