# Generated by Django 3.2.12 on 2022-03-02 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_transport_service', '0007_auto_20220302_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_transport_service.transportservicerequest', verbose_name='request'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_transport_service.transportserviceoffer', verbose_name='donation'),
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_transport_service.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='donor'),
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='has_disabled_access',
            field=models.BooleanField(default=False, verbose_name='has disabled access'),
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='has_refrigeration',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='has refrigeration'),
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='pets_allowed',
            field=models.BooleanField(default=False, verbose_name='pets allowed'),
        ),
        migrations.AlterField(
            model_name='transportservicerequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_transport_service.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='transportservicerequest',
            name='has_disabled_access',
            field=models.BooleanField(default=False, verbose_name='has disabled access'),
        ),
        migrations.AlterField(
            model_name='transportservicerequest',
            name='has_refrigeration',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='has refrigeration'),
        ),
        migrations.AlterField(
            model_name='transportservicerequest',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='requested by'),
        ),
        migrations.AlterField(
            model_name='transportservicerequest',
            name='pets_allowed',
            field=models.BooleanField(default=False, verbose_name='pets allowed'),
        ),
    ]
