# Generated by Django 3.2.12 on 2022-03-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_service', '0008_auto_20220302_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportserviceoffer',
            name='county_coverage',
        ),
    ]
