# Generated by Django 3.2.12 on 2022-03-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_service', '0009_remove_transportserviceoffer_county_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportserviceoffer',
            name='driver_contact',
            field=models.CharField(default='', max_length=255, verbose_name='contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='driver_id',
            field=models.CharField(max_length=255, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='transportserviceoffer',
            name='driver_name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
