# Generated by Django 3.2.12 on 2022-08-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_food_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrequest',
            name='child_restriction_notes',
            field=models.CharField(blank=True, default='', help_text='Gluten, lactose, salt... restrictions', max_length=255, verbose_name='child restriction notes'),
        ),
    ]
