# Generated by Django 3.2.12 on 2022-08-31 13:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_food_request', '0002_alter_foodrequest_child_restriction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrequest',
            name='offered_services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('HOST', 'hosting'), ('FOOD', 'food'), ('EDU', 'educational services'), ('MISC', 'other services')], max_length=18, null=True, verbose_name='offered services'),
        ),
        migrations.AddField(
            model_name='foodrequest',
            name='other_offered_services',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='other offered services'),
        ),
    ]
