# Generated by Django 3.2.12 on 2022-03-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_volunteering', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteeringoffer',
            options={'verbose_name': 'volunteering offer', 'verbose_name_plural': 'volunteering offers (0)'},
        ),
        migrations.AlterModelOptions(
            name='volunteeringrequest',
            options={'verbose_name': 'volunteering request', 'verbose_name_plural': 'volunteering request (0)'},
        ),
    ]
