# Generated by Django 3.2.12 on 2022-03-02 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_volunteering', '0002_auto_20220302_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteeringoffer',
            name='county_coverage',
        ),
        migrations.RemoveField(
            model_name='volunteeringrequest',
            name='county_coverage',
        ),
        migrations.AddField(
            model_name='volunteeringoffer',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified')], default='NV', max_length=5, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='volunteeringrequest',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified')], default='NV', max_length=5, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_volunteering.volunteeringrequest', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_volunteering.volunteeringoffer', verbose_name='made_by'),
        ),
        migrations.AlterField(
            model_name='volunteeringoffer',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='volunteeringoffer',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='donor'),
        ),
        migrations.AlterField(
            model_name='volunteeringoffer',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_volunteering.type', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='volunteeringrequest',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='volunteeringrequest',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='requested by'),
        ),
        migrations.AlterField(
            model_name='volunteeringrequest',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_volunteering.type', verbose_name='type'),
        ),
    ]
