# Generated by Django 3.2.12 on 2022-03-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_volunteering', '0003_auto_20220304_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteeringoffer',
            options={'verbose_name': 'volunteering offer', 'verbose_name_plural': 'volunteering offers'},
        ),
        migrations.AlterModelOptions(
            name='volunteeringrequest',
            options={'verbose_name': 'volunteering request', 'verbose_name_plural': 'volunteering request'},
        ),
    ]
