# Generated by Django 3.2.12 on 2022-03-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_volunteering', '0003_auto_20220302_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeringoffer',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='added on'),
        ),
        migrations.AlterField(
            model_name='volunteeringrequest',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='added on'),
        ),
    ]
