# Generated by Django 3.2.12 on 2022-03-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_volunteering', '0004_auto_20220305_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeringoffer',
            name='name',
            field=models.CharField(db_index=True, default='Cristi Sprijinescu', max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
    ]
