# Generated by Django 3.2.12 on 2022-03-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_volunteering', '0005_volunteeringoffer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeringoffer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
