# Generated by Django 3.2.12 on 2022-03-07 20:04

from django.db import migrations, models

import revm_site.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('app_volunteering', '0009_alter_volunteeringoffer_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeringoffer',
            name='available_until',
            field=models.DateField(null=True, validators=[revm_site.utils.validators.validate_date_disallow_past], verbose_name='volunteer available until'),
        ),
    ]
