# Generated by Django 3.2.12 on 2022-03-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transport_service', '0004_auto_20220304_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportserviceoffer',
            options={'verbose_name': 'transport service offer', 'verbose_name_plural': 'transport service offers'},
        ),
        migrations.AlterModelOptions(
            name='transportservicerequest',
            options={'verbose_name': 'transport service request', 'verbose_name_plural': 'transport service request'},
        ),
    ]
