# Generated by Django 3.2.12 on 2022-03-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cui_cif',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='CUI/CIF'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='contact name'),
        ),
    ]
