# Generated by Django 3.2.12 on 2022-03-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0002_auto_20220302_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cui_cif',
        ),
        migrations.AddField(
            model_name='customuser',
            name='identification_no',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='identification number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='bussiness name'),
        ),
    ]
