# Generated by Django 3.2.12 on 2022-03-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0002_customuser_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Individual'), (2, 'Corporate'), (3, 'Non-Profit'), (4, 'Government')], verbose_name='type'),
        ),
    ]
