# Generated by Django 3.2.12 on 2022-03-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_other', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otheroffer',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='otheroffer',
            name='expiration_date',
        ),
        migrations.AlterField(
            model_name='otheroffer',
            name='available_until',
            field=models.DateField(null=True, verbose_name='resource available until'),
        ),
        migrations.AlterField(
            model_name='otheroffer',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified'), ('D', 'Deactivated'), ('C', 'Complete')], default='NV', max_length=5, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='otherrequest',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified'), ('D', 'Deactivated'), ('C', 'Complete')], default='NV', max_length=5, verbose_name='status'),
        ),
    ]
