# Generated by Django 3.2.12 on 2022-03-02 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_other', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otheroffer',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='otherrequest',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='otheroffer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_other.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='otheroffer',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified')], default='NV', max_length=5, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='otherrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_other.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='otherrequest',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified')], default='NV', max_length=5, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='otheroffer',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='added on'),
        ),
        migrations.AlterField(
            model_name='otheroffer',
            name='county_coverage',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AB', 'Alba'), ('AR', 'Arad'), ('AG', 'Argeș'), ('BC', 'Bacău'), ('BH', 'Bihor'), ('BN', 'Bistrița-Năsăud'), ('BT', 'Botoșani'), ('BV', 'Brașov'), ('BR', 'Brăila'), ('B', 'București'), ('BZ', 'Buzău'), ('CL', 'Călărași'), ('CS', 'Caraș-Severin'), ('CJ', 'Cluj'), ('CT', 'Constanța'), ('CV', 'Covasna'), ('DB', 'Dâmbovița'), ('DJ', 'Dolj'), ('GL', 'Galați'), ('GR', 'Giurgiu'), ('GJ', 'Gorj'), ('HR', 'Harghita'), ('HD', 'Hunedoara'), ('IL', 'Ialomița'), ('IS', 'Iași'), ('IF', 'Ilfov'), ('MM', 'Maramureș'), ('MH', 'Mehedinți'), ('MS', 'Mureș'), ('NT', 'Neamț'), ('OT', 'Olt'), ('PH', 'Prahova'), ('SM', 'Satu Mare'), ('SJ', 'Sălaj'), ('SB', 'Sibiu'), ('SV', 'Suceava'), ('TR', 'Teleorman'), ('TM', 'Timiș'), ('TL', 'Tulcea'), ('VS', 'Vaslui'), ('VL', 'Vâlcea'), ('VN', 'Vrancea')], max_length=124, null=True, verbose_name='county coverage'),
        ),
        migrations.AlterField(
            model_name='otheroffer',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='otheroffer',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='donor'),
        ),
        migrations.AlterField(
            model_name='otheroffer',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='town'),
        ),
        migrations.AlterField(
            model_name='otherrequest',
            name='county_coverage',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AB', 'Alba'), ('AR', 'Arad'), ('AG', 'Argeș'), ('BC', 'Bacău'), ('BH', 'Bihor'), ('BN', 'Bistrița-Năsăud'), ('BT', 'Botoșani'), ('BV', 'Brașov'), ('BR', 'Brăila'), ('B', 'București'), ('BZ', 'Buzău'), ('CL', 'Călărași'), ('CS', 'Caraș-Severin'), ('CJ', 'Cluj'), ('CT', 'Constanța'), ('CV', 'Covasna'), ('DB', 'Dâmbovița'), ('DJ', 'Dolj'), ('GL', 'Galați'), ('GR', 'Giurgiu'), ('GJ', 'Gorj'), ('HR', 'Harghita'), ('HD', 'Hunedoara'), ('IL', 'Ialomița'), ('IS', 'Iași'), ('IF', 'Ilfov'), ('MM', 'Maramureș'), ('MH', 'Mehedinți'), ('MS', 'Mureș'), ('NT', 'Neamț'), ('OT', 'Olt'), ('PH', 'Prahova'), ('SM', 'Satu Mare'), ('SJ', 'Sălaj'), ('SB', 'Sibiu'), ('SV', 'Suceava'), ('TR', 'Teleorman'), ('TM', 'Timiș'), ('TL', 'Tulcea'), ('VS', 'Vaslui'), ('VL', 'Vâlcea'), ('VN', 'Vrancea')], max_length=124, null=True, verbose_name='county coverage'),
        ),
        migrations.AlterField(
            model_name='otherrequest',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='requested by'),
        ),
        migrations.AlterField(
            model_name='otherrequest',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='town'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_other.otherrequest', verbose_name='request'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_other.otheroffer', verbose_name='donation'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
