# Generated by Django 3.2.12 on 2022-03-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_other', '0002_auto_20220304_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='otheroffer',
            name='has_transportation',
            field=models.BooleanField(blank=True, null=True, verbose_name='has transportation'),
        ),
    ]
