# Generated by Django 3.2.12 on 2022-03-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_other', '0002_auto_20220303_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otheroffer',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified'), ('A', 'Active'), ('D', 'Deactivated'), ('C', 'Complete')], default='NV', max_length=5, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='otherrequest',
            name='status',
            field=models.CharField(choices=[('NV', 'Not Verified'), ('V', 'Verified'), ('A', 'Active'), ('D', 'Deactivated'), ('C', 'Complete')], default='NV', max_length=5, verbose_name='status'),
        ),
    ]
