# Generated by Django 3.2.12 on 2022-03-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_other', '0009_alter_otherrequest_made_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default=models.CharField(db_index=True, max_length=50, verbose_name='category name'), max_length=50, verbose_name='category name (English)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ro',
            field=models.CharField(default=models.CharField(db_index=True, max_length=50, verbose_name='category name'), max_length=50, verbose_name='category name (Romanian)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default=models.CharField(db_index=True, max_length=50, verbose_name='category name'), max_length=50, verbose_name='category name (Russian)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(default=models.CharField(db_index=True, max_length=50, verbose_name='category name'), max_length=50, verbose_name='category name (Ukrainian)'),
        ),
    ]
